#pragma once
const int playoff_dates_sz = 104;
const int fixture_dates_sz = 65;
const int league_team_list_sz = 59;

const vector<string> asia_east = {
	"Japan",
	"South Korea",
	"China",
	"Thailand",
	"Australia",
	"Malaysia",
	"Vietnam",
	"Hong Kong",
	"Singapore",
	"The Philippines",
	"Indonesia",
	"North Korea",
	"Cambodia",
	"Myanmar",
	"Chinese Taipei",
	"Mongolia",
	"Macau",
	"Laos",
	"Brunei Darussalam",
	"Guam",
	//"Northern Mariana Islands",
	"Timor",
};

const vector<string> asia_west = {
	"Saudi Arabia",
	"United Arab Emirates",
	"Qatar",
	"Iran",
	"Uzbekistan",
	"Iraq",
	"Jordan",
	"Bahrain",
	"India",
	"Tajikistan",
	"Turkmenistan",
	"Oman",
	"Lebanon",
	"Kuwait",
	"Bangladesh",
	"Syria",
	"Kyrgyzstan",
	"Maldives",
	"Palestine",
	"Nepal",
	"Sri Lanka",
	"Bhutan",
	"Afghanistan",
	"Pakistan",
	"Yemen",
};