#include "Helpers\Helper.h"
#include "inject_club_renames.h"

map<string, string> club_rename_short = {
	{"C.D. Ourense", "Ourense CF"},
};

map<string, string> club_rename_long = {
	{"Dallas Burn", "FC Dallas"},
	{"Kansas City Wizards", "Sporting Kansas City"},
	{"Miami Fusion FC", "Inter Miami CF"},
	{"NY/NJ Metrostars", "New York Red Bulls"},
	{"Tampa Bay Mutiny", "Los Angeles FC"},
	{"Clube Atlético Paranaense", "Club Athletico Paranaense"},
	{"C.D. Ourense", "Ourense CF"},
	{"C.P. Mérida", "AD Mérida"},
	{"Baskonia C.D.", "CD Basconia"},
	{"Extremadura C.F.", "CD Extremadura"},
	{"Merthyr Tydfil", "Merthyr Town"},
	{"Bra", "AC Bra"},
	{"AZ", "AZ Alkmaar"},
};

multimap<char*, DWORD> league_dword_match_nicks = {
	{"French Championnat National 3", (DWORD)0x9CF548},
	{"German Bundesliga", (DWORD)0x9CF54C},
	{"German 2. Bundesliga", (DWORD)0x9CF550},
	{"German 3. Liga West", (DWORD)0x9CF554},
	{"German 3. Liga Osten", (DWORD)0x9CF558},
	{"German 3. Liga Nord", (DWORD)0x9CF55C},
	{"German 3. Liga Süd", (DWORD)0x9CF560},
	{"German 3. Liga", (DWORD)0x9CF564},
	{"Dutch Eredivisie", (DWORD)0x9CF568},
	{"Dutch Eerste Divisie", (DWORD)0x9CF56C},
	{"Italian Serie A", (DWORD)0x9CF570},
	{"Italian Serie B", (DWORD)0x9CF574},
	{"Italian Serie C1/A", (DWORD)0x9CF578},
	{"Italian Serie C1/B", (DWORD)0x9CF57C},
	{"Italian Serie C2/A", (DWORD)0x9CF580},
	{"Italian Serie C2/B", (DWORD)0x9CF584},
	{"Italian Serie C2/C", (DWORD)0x9CF588},
	{"Italian Serie D", (DWORD)0x9CF58C},
	{"Major League Soccer", (DWORD)0x9CF590},
	{"American USL Championship", (DWORD)0x9CF594},
	{"American USL League One", (DWORD)0x9CF598},
	{"Belgian Pro League", (DWORD)0x9CF59C},
	{"Belgian Challenger Pro League", (DWORD)0x9CF5A0},
	{"Belgian National Division 1 A", (DWORD)0x9CF5A4},
	{"Belgian National Division 1 B", (DWORD)0x9CF5A8},
	{"Danish Superliga", (DWORD)0x9CF5AC},
	{"Danish First Division", (DWORD)0x9CF5B0},
	{"Danish Second Division", (DWORD)0x9CF5B4},
	{"Danish Third Division", (DWORD)0x9CF5B8},
	{"English Premier League", (DWORD)0x9CF5BC},
	{"English Football League Championship", (DWORD)0x9CF5C0},
	{"English Football League One", (DWORD)0x9CF5C4},
	{"English Football League Two", (DWORD)0x9CF5C8},
	{"French Ligue 1", (DWORD)0x9CF5CC},
	{"French Ligue 2", (DWORD)0x9CF5D0},
	{"French Championnat National 1", (DWORD)0x9CF5D4},
	{"French Championnat National 2", (DWORD)0x9CF5D8},
	{"Scottish Premiership", (DWORD)0x9CF5DC},
	{"Scottish Championship", (DWORD)0x9CF5E0},
	{"Scottish League One", (DWORD)0x9CF5E4},
	{"Scottish League Two", (DWORD)0x9CF5E8},
	{"Swedish Allsvenskan", (DWORD)0x9CF5EC},
	{"Swedish Superettan", (DWORD)0x9CF5F0},
	{"Swedish Ettan South Gotaland", (DWORD)0x9CF5F4},
	{"Swedish Ettan North", (DWORD)0x9CF5F8},
	{"Swedish Ettan East Svealand", (DWORD)0x9CF5FC},
	{"Swedish Ettan East Gotaland", (DWORD)0x9CF600},
	{"Swedish Ettan West Svealand", (DWORD)0x9CF604},
	{"Swedish Ettan West Gotaland", (DWORD)0x9CF608},
	{"Liga Portugal 1", (DWORD)0x9CF60C},
	{"Liga Portugal 2", (DWORD)0x9CF610},
	{"Liga 3 North", (DWORD)0x9CF614},
	{"Liga 3 Central", (DWORD)0x9CF618},
	{"Liga 3 South", (DWORD)0x9CF61C},
	{"Campeonato de Portugal", (DWORD)0x9CF620},
	{"Spanish La Liga", (DWORD)0x9CF624},
	{"Spanish La Liga 2", (DWORD)0x9CF628},
	{"Spanish Primera Federación Group 1", (DWORD)0x9CF62C},
	{"Spanish Primera Federación Group 2", (DWORD)0x9CF630},
	{"Spanish Primera Federación Group 3", (DWORD)0x9CF634},
	{"Spanish Primera Federación Group 4", (DWORD)0x9CF638},
	{"Copa Libertadores de América", (DWORD)0x9CF63C},
	{"Supercopa Libertadores", (DWORD)0x9CF640},
	{"Copa CONMEBOL", (DWORD)0x9CF644},
	{"Recopa Sudamericana", (DWORD)0x9CF648},
	{"AFC Champions League Elite", (DWORD)0x9CF64C},
	{"AFC Champions League Two", (DWORD)0x9CF650},
	{"Argentine Primera División", (DWORD)0x9CF654},
	{"Argentine Primera Nacional", (DWORD)0x9CF658},
	{"Japanese J1 League", (DWORD)0x9CF65C},
	{"Japanese Emperor's Cup", (DWORD)0x9CF660},
	{"Japanese J.League Cup", (DWORD)0x9CF664},
	{"Friendly", (DWORD)0x9CF668},
	{"Japanese Super Cup", (DWORD)0x9CF66C},
	{"Japanese J3 League", (DWORD)0x9CF670},
	{"Japanese University League", (DWORD)0x9CF674},
	{"Japanese Regional Leagues", (DWORD)0x9CF678},
	{"Copa Argentina", (DWORD)0x9CF67C},
	{"Argentine Interior Zone", (DWORD)0x9CF680},
	{"Reserve", (DWORD)0x9CF684},
	{"Argentine Third Division", (DWORD)0x9CF688},
	{"Merconorte Cup", (DWORD)0x9CF68C},
	{"MLS All-Stars", (DWORD)0x9CF690},
	{"German DFL-Supercup", (DWORD)0x9CF694},
	{"Copa Sudamericana", (DWORD)0x9CF698},
	{"English National League", (DWORD)0x9CF69C},
	{"English FA Trophy", (DWORD)0x9CF6A0},
	{"Conference League Cup", (DWORD)0x9CF6A4},
	{"Trophée des Champions", (DWORD)0x9CF6A8},
	{"Swedish Division 3", (DWORD)0x9CF6AC},
	{"Spanish Segunda Federación", (DWORD)0x9CF6B0},
	{"Supertaça Cândido de Oliveira", (DWORD)0x9CF6B4},
	{"A Premier Division", (DWORD)0x9CF6B8},
	{"Norwegian Eliteserien", (DWORD)0x9CF6BC},
	{"Norwegian 1. Divisjon", (DWORD)0x9CF6C0},
	{"Norwegian 2. Divisjon Group 1", (DWORD)0x9CF6C4},
	{"Norwegian 2. Divisjon Group 2", (DWORD)0x9CF6C8},
	{"Norwegian 2. Divisjon Group 3", (DWORD)0x9CF6CC},
	{"Norwegian 2. Divisjon Group 4", (DWORD)0x9CF6D0},
	{"Norwegian 2. Divisjon Group 5", (DWORD)0x9CF6D4},
	{"Norwegian 2. Divisjon Group 6", (DWORD)0x9CF6D8},
	{"Norwegian 2. Divisjon Group 7", (DWORD)0x9CF6DC},
	{"Norwegian 2. Divisjon Group 8", (DWORD)0x9CF6E0},
	{"Intercontinental Cup", (DWORD)0x9CF6E4},
	{"UEFA Champions League", (DWORD)0x9CF6E8},
	{"UEFA Cup Winners Cup", (DWORD)0x9CF6EC},
	{"UEFA Europa League", (DWORD)0x9CF6F0},
	{"UEFA Super Cup", (DWORD)0x9CF6F4},
	{"UEFA Europa League Qualifying", (DWORD)0x9CF6F8},
	{"Supercoupe de Belgique", (DWORD)0x9CF6FC},
	{"Coupe de Belgique", (DWORD)0x9CF700},
	{"Belgian League Cup", (DWORD)0x9CF704},
	{"DBU Pokalen", (DWORD)0x9CF708},
	{"Coupe de France", (DWORD)0x9CF70C},
	{"Coupe de la Ligue", (DWORD)0x9CF710},
	{"German DFB-Pokal", (DWORD)0x9CF714},
	{"KNVB Beker", (DWORD)0x9CF718},
	{"Coppa Italia", (DWORD)0x9CF71C},
	{"Coppa Italia Serie C", (DWORD)0x9CF720},
	{"Supercoppa Italiana", (DWORD)0x9CF724},
	{"Lamar Hunt U.S. Open Cup", (DWORD)0x9CF728},
	{"CONCACAF Champions Cup", (DWORD)0x9CF72C},
	{"CONCACAF Cup Winners Cup", (DWORD)0x9CF730},
	{"Norwegian Cupen", (DWORD)0x9CF734},
	{"Norwegian 3. Divisjon", (DWORD)0x9CF738},
	{"Taça de Portugal", (DWORD)0x9CF73C},
	{"Spanish Copa del Rey", (DWORD)0x9CF740},
	{"Supercopa de España", (DWORD)0x9CF744},
	{"Svenska Cupen", (DWORD)0x9CF748},
	{"English FA Cup", (DWORD)0x9CF74C},
	{"English League Cup", (DWORD)0x9CF750},
	{"English FA Community Shield", (DWORD)0x9CF754},
	{"English Football League Trophy", (DWORD)0x9CF758},
	{"Scottish Cup", (DWORD)0x9CF75C},
	{"Scottish League Cup", (DWORD)0x9CF760},
	{"A Lower Division", (DWORD)0x9CF764},
	{"Japanese J2 League", (DWORD)0x9CF768},
	{"World Cup Oceania Qualifying Section", (DWORD)0x9CF76C},
	{"World Cup CONCACAF Qualifying Section", (DWORD)0x9CF770},
	{"World Cup Asian Qualifying Section", (DWORD)0x9CF774},
	{"World Cup South American Qualifying Section", (DWORD)0x9CF778},
	{"World Cup African Qualifying Section", (DWORD)0x9CF77C},
	{"World Cup European Qualifying Section", (DWORD)0x9CF780},
	{"UEFA European Championship Qualifying", (DWORD)0x9CF784},
	{"Asian Cup Qualifying", (DWORD)0x9CF788},
	{"Asian Games Football Tournament", (DWORD)0x9CF78C},
	{"AFC Asian Cup", (DWORD)0x9CF790},
	{"\'B\' International", (DWORD)0x9CF794},
	{"Under 21 International", (DWORD)0x9CF798},
	{"FIFA World Cup", (DWORD)0x9CF79C},
	{"Olympic Games", (DWORD)0x9CF7A0},
	{"UEFA European Championship", (DWORD)0x9CF7A4},
	{"Copa América", (DWORD)0x9CF7A8},
	{"African Cup of Nations", (DWORD)0x9CF7AC},
	{"Johan Cruijff Schaal", (DWORD)0x9CF7B0},
	{"Scottish League Challenge Cup", (DWORD)0x9CF7B4},
	{"Spanish Primera Federación", (DWORD)0x9CF7B8},
	{"FIFA Club World Cup", (DWORD)0x9CF7BC},
	{"Liga 3", (DWORD)0x9CF7C0},
	{"Belgian National Division 1", (DWORD)0x9CF7C4},
	{"Swedish Ettan", (DWORD)0x9CF7C8},
	{"OFC Champions League", (DWORD)0x9CF7CC},
	{"Asian Super Cup", (DWORD)0x9CF7D0},
	{"Belgian Division 2 A", (DWORD)0x9CF7D4},
	{"Belgian Division 2 B", (DWORD)0x9CF7D8},
	{"Belgian Division 2 C", (DWORD)0x9CF7DC},
	{"Belgian Division 2 D", (DWORD)0x9CF7E0},
	{"Suomen Cup", (DWORD)0x9CF7E4},
	{"Finnish Veikkausliiga", (DWORD)0x9CF7E8},
	{"Finnish Ykkösliiga North", (DWORD)0x9CF7EC},
	{"Finnish Ykkösliiga South", (DWORD)0x9CF7F0},
	{"Finnish Kakkonen", (DWORD)0x9CF7F4},
	{"Finnish Ykkösliiga", (DWORD)0x9CF7F8},
	{"Finnish Ykkönen North", (DWORD)0x9CF7FC},
	{"Finnish Ykkönen West", (DWORD)0x9CF800},
	{"Finnish Ykkönen South", (DWORD)0x9CF804},
	{"Finnish Ykkönen East", (DWORD)0x9CF808},
	{"League of Ireland Premier Division", (DWORD)0x9CF80C},
	{"League of Ireland First Division", (DWORD)0x9CF810},
	{"Irish Group A", (DWORD)0x9CF814},
	{"Irish Group B", (DWORD)0x9CF818},
	{"Irish Group C", (DWORD)0x9CF81C},
	{"Irish Group D", (DWORD)0x9CF820},
	{"Irish Group E", (DWORD)0x9CF824},
	{"Northern Irish Group A", (DWORD)0x9CF82C},
	{"Northern Irish Group B", (DWORD)0x9CF830},
	{"Northern Irish Group C", (DWORD)0x9CF834},
	{"Northern Irish Group D", (DWORD)0x9CF838},
	{"League of Ireland Cup", (DWORD)0x9CF83C},
	{"FAI Cup", (DWORD)0x9CF840},
	{"Irish Super Cup", (DWORD)0x9CF844},
	{"Irish Connacht Senior League", (DWORD)0x9CF848},
	{"Irish Ulster Senior League", (DWORD)0x9CF84C},
	{"Irish Munster Senior League", (DWORD)0x9CF850},
	{"Irish Leinster Senior League Premier", (DWORD)0x9CF854},
	{"Polish Ekstraklasa", (DWORD)0x9CF858},
	{"Polish I Liga", (DWORD)0x9CF85C},
	{"Puchar Ekstraklasa", (DWORD)0x9CF860},
	{"Puchar Polski", (DWORD)0x9CF864},
	{"Polish II Liga", (DWORD)0x9CF868},
	{"Greek Super League", (DWORD)0x9CF86C},
	{"Greek Super League 2", (DWORD)0x9CF870},
	{"Greek Gamma Ethniki", (DWORD)0x9CF874},
	{"Kypello Elladas", (DWORD)0x9CF878},
	{"Croatian HNL", (DWORD)0x9CF87C},
	{"Croatian Prva NL", (DWORD)0x9CF880},
	{"Croatian Druga NL Central", (DWORD)0x9CF884},
	{"Croatian Druga NL North", (DWORD)0x9CF888},
	{"Croatian Druga NL South", (DWORD)0x9CF88C},
	{"Croatian Druga NL East", (DWORD)0x9CF890},
	{"Croatian Druga NL West", (DWORD)0x9CF894},
	{"Hrvatski Kup", (DWORD)0x9CF898},
	{"Australian A-League", (DWORD)0x9CF89C},
	{"OFC Nations Cup", (DWORD)0x9CF8A0},
	{"Croatian HNL", (DWORD)0x9CF8A4},
	{"Croatian Prva NL North", (DWORD)0x9CF8A8},
	{"Croatian Prva NL South", (DWORD)0x9CF8AC},
	{"NIFL Premiership", (DWORD)0x9CF8B0},
	{"NIFL Championship", (DWORD)0x9CF8B4},
	{"NIFL Premier Intermediate League", (DWORD)0x9CF8B8},
	{"NIFL Charity Shield", (DWORD)0x9CF8BC},
	{"Irish Football Association Challenge Cup", (DWORD)0x9CF8C0},
	{"Northern Irish Gold Cup", (DWORD)0x9CF8C4},
	{"Irish Football League Cup", (DWORD)0x9CF8C8},
	{"TFF 3. Lig", (DWORD)0x9CF8CC},
	{"TFF 1. Lig", (DWORD)0x9CF8D0},
	{"TFF 2. Lig", (DWORD)0x9CF8D4},
	{"Turkish Süper Lig", (DWORD)0x9CF8D8},
	{"TFF 1. Lig", (DWORD)0x9CF8DC},
	{"TFF 2. Lig", (DWORD)0x9CF8E0},
	{"TFF 2. Lig G1", (DWORD)0x9CF8E4},
	{"TFF 2. Lig G2", (DWORD)0x9CF8E8},
	{"TFF 2. Lig G3", (DWORD)0x9CF8EC},
	{"TFF 2. Lig G4", (DWORD)0x9CF8F0},
	{"TFF 2. Lig G5", (DWORD)0x9CF8F4},
	{"Türkiye Kupasi", (DWORD)0x9CF8F8},
	{"Turkish Football Writers' Association Cup", (DWORD)0x9CF8FC},
	{"Turkish 2. Division Group 1", (DWORD)0x9CF900},
	{"Turkish 2. Division Group 2", (DWORD)0x9CF904},
	{"Turkish 2. Division Group 3", (DWORD)0x9CF908},
	{"Turkish 2. Division Group 4", (DWORD)0x9CF90C},
	{"Turkish 2. Division Group 5", (DWORD)0x9CF910},
	{"Russian Second Division - West", (DWORD)0x9CF914},
	{"Russian Second Division - Central", (DWORD)0x9CF918},
	{"Russian Second Division - South", (DWORD)0x9CF91C},
	{"Russian Second Division - Volga", (DWORD)0x9CF920},
	{"Russian Second Division - Ural", (DWORD)0x9CF924},
	{"Russian Second Division - East", (DWORD)0x9CF928},
	{"Russian First Division", (DWORD)0x9CF92C},
	{"Russian Premier Division", (DWORD)0x9CF930},
	{"Russian Cup", (DWORD)0x9CF934},
	{"Supercoppa Serie C", (DWORD)0x9CF938},
	{"Greek Super Cup", (DWORD)0x9CF93C},
	{"Croatian Super Cup", (DWORD)0x9CF940},
	{"Superpuchar Polski", (DWORD)0x9CF944},
	{"Irish Presidents Cup", (DWORD)0x9CF948},
	{"Welsh Cymru Premier", (DWORD)0x9CF94C},
	{"Welsh Cymru Premier League Cup", (DWORD)0x9CF950},
	{"FAW Welsh Cup", (DWORD)0x9CF954},
	{"Welsh FAW Premier Cup", (DWORD)0x9CF958},
	{"Copa Interamericana", (DWORD)0x9CF95C},
	{"Welsh Lower Division", (DWORD)0x9CF960},
	{"FIFA Confederations Cup", (DWORD)0x9CF964},
	{"Brazilian Bahia Lower Division", (DWORD)0x9CF968},
	{"Brazilian Central Lower Division", (DWORD)0x9CF96C},
	{"Brazilian Santa Catarina Lower Division", (DWORD)0x9CF970},
	{"Brazilian Pernambuco Lower Division", (DWORD)0x9CF974},
	{"Brazilian North Lower Division", (DWORD)0x9CF978},
	{"Brazilian Rio de Janeiro Lower Division", (DWORD)0x9CF97C},
	{"Brazilian Northeast Lower Division", (DWORD)0x9CF980},
	{"Brazilian Goiás Lower Division", (DWORD)0x9CF984},
	{"Brazilian Minas Gerais Lower Division", (DWORD)0x9CF988},
	{"Brazilian Paraná Lower Division", (DWORD)0x9CF98C},
	{"Brazilian Gaúcho Lower Division", (DWORD)0x9CF990},
	{"Brazilian Campeonato do Norte", (DWORD)0x9CF994},
	{"Brazilian Campeonato Central", (DWORD)0x9CF998},
	{"Brazilian São Paulo Lower Division", (DWORD)0x9CF99C},
	{"Brazilian Copa Central", (DWORD)0x9CF9A0},
	{"Brazilian Campeonato do Nordeste", (DWORD)0x9CF9A4},
	{"Brazilian Copa Norte", (DWORD)0x9CF9A8},
	{"Campeonato Brasileiro Série C", (DWORD)0x9CF9AC},
	{"Brazilian Campeonato Catarinense", (DWORD)0x9CF9B0},
	{"Brazilian Campeonato Goiano", (DWORD)0x9CF9B4},
	{"Brazilian Copa dos Campeões", (DWORD)0x9CF9B8},
	{"Brazilian Campeonato Pernambucano", (DWORD)0x9CF9BC},
	{"Brazilian Campeonato Baiano", (DWORD)0x9CF9C0},
	{"Brazilian Copa do Nordeste", (DWORD)0x9CF9C4},
	{"Brazilian Campeonato Gaúcho", (DWORD)0x9CF9C8},
	{"Brazilian Copa Sul-Minas", (DWORD)0x9CF9CC},
	{"Brazilian Campeonato Paranaense", (DWORD)0x9CF9D0},
	{"Brazilian Campeonato Mineiro", (DWORD)0x9CF9D4},
	{"Brazilian Torneio Rio-São Paulo", (DWORD)0x9CF9D8},
	{"Brazilian Campeonato Carioca", (DWORD)0x9CF9DC},
	{"Campeonato Brasileiro Série B", (DWORD)0x9CF9E0},
	{"Brazilian Campeonato Paulista", (DWORD)0x9CF9E4},
	{"Copa do Brasil", (DWORD)0x9CF9E8},
	{"Campeonato Brasileiro Série A", (DWORD)0x9CF9EC},
	{"Irish Munster Senior Cup", (DWORD)0x9CF9F0},
	{"Irish Leinster Senior Cup", (DWORD)0x9CF9F4},
	{"Korean Super Cup", (DWORD)0x9CF9F8},
	{"Korean League Cup", (DWORD)0x9CF9FC},
	{"K League 1", (DWORD)0x9CFA00},
	{"Korean FA Cup", (DWORD)0x9CFA04},
};

multimap<char*, DWORD> league_dword_match_original = {
	{"French Lower Division", (DWORD)0x9CF548},
	{"German First Division", (DWORD)0x9CF54C},
	{"German Second Division", (DWORD)0x9CF550},
	{"German Regional Division West/Southwest", (DWORD)0x9CF554},
	{"German Regional Division East", (DWORD)0x9CF558},
	{"German Regional Division North", (DWORD)0x9CF55C},
	{"German Regional Division South", (DWORD)0x9CF560},
	{"German Regional", (DWORD)0x9CF564},
	{"Dutch Premier Division", (DWORD)0x9CF568},
	{"Dutch First Division", (DWORD)0x9CF56C},
	{"Italian Serie A", (DWORD)0x9CF570},
	{"Italian Serie B", (DWORD)0x9CF574},
	{"Italian Serie C1/A", (DWORD)0x9CF578},
	{"Italian Serie C1/B", (DWORD)0x9CF57C},
	{"Italian Serie C2/A", (DWORD)0x9CF580},
	{"Italian Serie C2/B", (DWORD)0x9CF584},
	{"Italian Serie C2/C", (DWORD)0x9CF588},
	{"Italian Serie D", (DWORD)0x9CF58C},
	{"American Major League", (DWORD)0x9CF590},
	{"American A-League", (DWORD)0x9CF594},
	{"American D3-Pro League", (DWORD)0x9CF598},
	{"Belgian First Division", (DWORD)0x9CF59C},
	{"Belgian Second Division", (DWORD)0x9CF5A0},
	{"Belgian Third Division A", (DWORD)0x9CF5A4},
	{"Belgian Third Division B", (DWORD)0x9CF5A8},
	{"Danish Premier Division", (DWORD)0x9CF5AC},
	{"Danish First Division", (DWORD)0x9CF5B0},
	{"Danish Second Division", (DWORD)0x9CF5B4},
	{"Danish Kvalifikationsrækken", (DWORD)0x9CF5B8},
	{"English Premier Division", (DWORD)0x9CF5BC},
	{"English First Division", (DWORD)0x9CF5C0},
	{"English Second Division", (DWORD)0x9CF5C4},
	{"English Third Division", (DWORD)0x9CF5C8},
	{"French First Division", (DWORD)0x9CF5CC},
	{"French Second Division", (DWORD)0x9CF5D0},
	{"French National", (DWORD)0x9CF5D4},
	{"French CFA", (DWORD)0x9CF5D8},
	{"Scottish Premier Division", (DWORD)0x9CF5DC},
	{"Scottish First Division", (DWORD)0x9CF5E0},
	{"Scottish Second Division", (DWORD)0x9CF5E4},
	{"Scottish Third Division", (DWORD)0x9CF5E8},
	{"Swedish Premier Division", (DWORD)0x9CF5EC},
	{"Swedish First Division", (DWORD)0x9CF5F0},
	{"Swedish Second Division South Gotaland", (DWORD)0x9CF5F4},
	{"Swedish Second Division North", (DWORD)0x9CF5F8},
	{"Swedish Second Division East Svealand", (DWORD)0x9CF5FC},
	{"Swedish Second Division East Gotaland", (DWORD)0x9CF600},
	{"Swedish Second Division West Svealand", (DWORD)0x9CF604},
	{"Swedish Second Division West Gotaland", (DWORD)0x9CF608},
	{"Portuguese Premier League", (DWORD)0x9CF60C},
	{"Portuguese Second League", (DWORD)0x9CF610},
	{"Portuguese Second Division B North", (DWORD)0x9CF614},
	{"Portuguese Second Division B Central", (DWORD)0x9CF618},
	{"Portuguese Second Division B South", (DWORD)0x9CF61C},
	{"Portuguese Third Division", (DWORD)0x9CF620},
	{"Spanish First Division", (DWORD)0x9CF624},
	{"Spanish Second Division", (DWORD)0x9CF628},
	{"Spanish Second Division B1", (DWORD)0x9CF62C},
	{"Spanish Second Division B2", (DWORD)0x9CF630},
	{"Spanish Second Division B3", (DWORD)0x9CF634},
	{"Spanish Second Division B4", (DWORD)0x9CF638},
	{"South American Copa Libertadores", (DWORD)0x9CF63C},
	{"South American Super Cup", (DWORD)0x9CF640},
	{"South American CONMEBOL Cup", (DWORD)0x9CF644},
	{"South American Recopa", (DWORD)0x9CF648},
	{"Asian Club Championship", (DWORD)0x9CF64C},
	{"Asian Cup Winners\' Cup", (DWORD)0x9CF650},
	{"Argentine Premier Division", (DWORD)0x9CF654},
	{"Argentine Second Division", (DWORD)0x9CF658},
	{"Japanese J-League 1", (DWORD)0x9CF65C},
	{"Japanese Emperor's Cup", (DWORD)0x9CF660},
	{"Japanese Cup", (DWORD)0x9CF664},
	{"Friendly", (DWORD)0x9CF668},
	{"Japanese Super Cup", (DWORD)0x9CF66C},
	{"Japanese Football League", (DWORD)0x9CF670},
	{"Japanese University League", (DWORD)0x9CF674},
	{"Japanese Administrative Division", (DWORD)0x9CF678},
	{"Argentine Metropolitan Zone", (DWORD)0x9CF67C},
	{"Argentine Interior Zone", (DWORD)0x9CF680},
	{"Reserve", (DWORD)0x9CF684},
	{"Argentine Third Division", (DWORD)0x9CF688},
	{"Merconorte Cup", (DWORD)0x9CF68C},
	{"American MLS All-Stars", (DWORD)0x9CF690},
	{"German League Cup", (DWORD)0x9CF694},
	{"South American Copa Mercosur", (DWORD)0x9CF698},
	{"English Conference", (DWORD)0x9CF69C},
	{"English FA Trophy", (DWORD)0x9CF6A0},
	{"English Conference Cup", (DWORD)0x9CF6A4},
	{"French Champions Trophy", (DWORD)0x9CF6A8},
	{"Swedish Lower Division", (DWORD)0x9CF6AC},
	{"Spanish Lower Division", (DWORD)0x9CF6B0},
	{"Portuguese Super Cup", (DWORD)0x9CF6B4},
	{"A Premier Division", (DWORD)0x9CF6B8},
	{"Norwegian Premier Division", (DWORD)0x9CF6BC},
	{"Norwegian First Division", (DWORD)0x9CF6C0},
	{"Norwegian Second Division Group 1", (DWORD)0x9CF6C4},
	{"Norwegian Second Division Group 2", (DWORD)0x9CF6C8},
	{"Norwegian Second Division Group 3", (DWORD)0x9CF6CC},
	{"Norwegian Second Division Group 4", (DWORD)0x9CF6D0},
	{"Norwegian Second Division Group 5", (DWORD)0x9CF6D4},
	{"Norwegian Second Division Group 6", (DWORD)0x9CF6D8},
	{"Norwegian Second Division Group 7", (DWORD)0x9CF6DC},
	{"Norwegian Second Division Group 8", (DWORD)0x9CF6E0},
	{"Intercontinental Cup", (DWORD)0x9CF6E4},
	{"European Champions Cup", (DWORD)0x9CF6E8},
	{"European Cup Winners Cup", (DWORD)0x9CF6EC},
	{"UEFA Cup", (DWORD)0x9CF6F0},
	{"European Super Cup", (DWORD)0x9CF6F4},
	{"Inter-Toto Cup", (DWORD)0x9CF6F8},
	{"Belgian Super Cup", (DWORD)0x9CF6FC},
	{"Belgian Cup", (DWORD)0x9CF700},
	{"Belgian League Cup", (DWORD)0x9CF704},
	{"Danish Cup", (DWORD)0x9CF708},
	{"French Cup", (DWORD)0x9CF70C},
	{"French League Cup", (DWORD)0x9CF710},
	{"German Cup", (DWORD)0x9CF714},
	{"Dutch Cup", (DWORD)0x9CF718},
	{"Italian Cup", (DWORD)0x9CF71C},
	{"Italian Serie C Cup", (DWORD)0x9CF720},
	{"Italian Super Cup", (DWORD)0x9CF724},
	{"US Open Cup", (DWORD)0x9CF728},
	{"CONCACAF Champions Cup", (DWORD)0x9CF72C},
	{"CONCACAF Cup Winners Cup", (DWORD)0x9CF730},
	{"Norwegian Cup", (DWORD)0x9CF734},
	{"Norwegian Third Division", (DWORD)0x9CF738},
	{"Portuguese Cup", (DWORD)0x9CF73C},
	{"Spanish Cup", (DWORD)0x9CF740},
	{"Spanish Super Cup", (DWORD)0x9CF744},
	{"Swedish Cup", (DWORD)0x9CF748},
	{"English FA Cup", (DWORD)0x9CF74C},
	{"English League Cup", (DWORD)0x9CF750},
	{"English Charity Shield", (DWORD)0x9CF754},
	{"English Vans Trophy", (DWORD)0x9CF758},
	{"Scottish Cup", (DWORD)0x9CF75C},
	{"Scottish League Cup", (DWORD)0x9CF760},
	{"A Lower Division", (DWORD)0x9CF764},
	{"Japanese J-League 2", (DWORD)0x9CF768},
	{"World Cup Oceania Qualifying Section", (DWORD)0x9CF76C},
	{"World Cup CONCACAF Qualifying Section", (DWORD)0x9CF770},
	{"World Cup Asian Qualifying Section", (DWORD)0x9CF774},
	{"World Cup South American Qualifying Section", (DWORD)0x9CF778},
	{"World Cup African Qualifying Section", (DWORD)0x9CF77C},
	{"World Cup European Qualifying Section", (DWORD)0x9CF780},
	{"European Championship Qualifying", (DWORD)0x9CF784},
	{"Asian Cup Qualifying", (DWORD)0x9CF788},
	{"Asian Games Football Tournament", (DWORD)0x9CF78C},
	{"Asian Cup", (DWORD)0x9CF790},
	{"\'B\' International", (DWORD)0x9CF794},
	{"Under 21 International", (DWORD)0x9CF798},
	{"FIFA World Cup", (DWORD)0x9CF79C},
	{"Olympic Games", (DWORD)0x9CF7A0},
	{"European Football Championship", (DWORD)0x9CF7A4},
	{"Copa America", (DWORD)0x9CF7A8},
	{"African Cup of Nations", (DWORD)0x9CF7AC},
	{"Dutch Super Cup", (DWORD)0x9CF7B0},
	{"Scottish League Challenge Cup", (DWORD)0x9CF7B4},
	{"Spanish Second Division B", (DWORD)0x9CF7B8},
	{"FIFA Club World Championship", (DWORD)0x9CF7BC},
	{"Portuguese Second Division B", (DWORD)0x9CF7C0},
	{"Belgian Third Division", (DWORD)0x9CF7C4},
	{"Swedish Second Division", (DWORD)0x9CF7C8},
	{"Oceania Champions Cup", (DWORD)0x9CF7CC},
	{"Asian Super Cup", (DWORD)0x9CF7D0},
	{"Belgian Fourth Division  A", (DWORD)0x9CF7D4},
	{"Belgian Fourth Division  B", (DWORD)0x9CF7D8},
	{"Belgian Fourth Division  C", (DWORD)0x9CF7DC},
	{"Belgian Fourth Division  D", (DWORD)0x9CF7E0},
	{"Finnish Cup", (DWORD)0x9CF7E4},
	{"Finnish Premier Division", (DWORD)0x9CF7E8},
	{"Finnish First Division North", (DWORD)0x9CF7EC},
	{"Finnish First Division South", (DWORD)0x9CF7F0},
	{"Finnish Lower Division", (DWORD)0x9CF7F4},
	{"Finnish First Division", (DWORD)0x9CF7F8},
	{"Finnish Second Division North", (DWORD)0x9CF7FC},
	{"Finnish Second Division West", (DWORD)0x9CF800},
	{"Finnish Second Division South", (DWORD)0x9CF804},
	{"Finnish Second Division East", (DWORD)0x9CF808},
	{"Irish Premier Division", (DWORD)0x9CF80C},
	{"Irish First Division", (DWORD)0x9CF810},
	{"Irish Group A", (DWORD)0x9CF814},
	{"Irish Group B", (DWORD)0x9CF818},
	{"Irish Group C", (DWORD)0x9CF81C},
	{"Irish Group D", (DWORD)0x9CF820},
	{"Irish Group E", (DWORD)0x9CF824},
	{"Northern Irish Group A", (DWORD)0x9CF82C},
	{"Northern Irish Group B", (DWORD)0x9CF830},
	{"Northern Irish Group C", (DWORD)0x9CF834},
	{"Northern Irish Group D", (DWORD)0x9CF838},
	{"Irish League Cup", (DWORD)0x9CF83C},
	{"Irish Senior Challenge Cup", (DWORD)0x9CF840},
	{"Irish Super Cup", (DWORD)0x9CF844},
	{"Irish Connacht Senior League", (DWORD)0x9CF848},
	{"Irish Ulster Senior League", (DWORD)0x9CF84C},
	{"Irish Munster Senior League", (DWORD)0x9CF850},
	{"Irish Leinster Senior League Premier", (DWORD)0x9CF854},
	{"Polish First Division", (DWORD)0x9CF858},
	{"Polish Second Division", (DWORD)0x9CF85C},
	{"Polish League Cup", (DWORD)0x9CF860},
	{"Polish FA Cup", (DWORD)0x9CF864},
	{"Polish Lower Division", (DWORD)0x9CF868},
	{"Greek National A Division", (DWORD)0x9CF86C},
	{"Greek National B Division", (DWORD)0x9CF870},
	{"Greek Lower Division", (DWORD)0x9CF874},
	{"Greek Cup", (DWORD)0x9CF878},
	{"Croatian First Division", (DWORD)0x9CF87C},
	{"Croatian Second Division", (DWORD)0x9CF880},
	{"Croatian Third Division Central", (DWORD)0x9CF884},
	{"Croatian Third Division North", (DWORD)0x9CF888},
	{"Croatian Third Division South", (DWORD)0x9CF88C},
	{"Croatian Third Division East", (DWORD)0x9CF890},
	{"Croatian Third Division West", (DWORD)0x9CF894},
	{"Croatian Cup", (DWORD)0x9CF898},
	{"Australian National Soccer League", (DWORD)0x9CF89C},
	{"Oceania Nations Cup", (DWORD)0x9CF8A0},
	{"Croatian First Division", (DWORD)0x9CF8A4},
	{"Croatian Second Division North", (DWORD)0x9CF8A8},
	{"Croatian Second Division South", (DWORD)0x9CF8AC},
	{"Northern Irish League Premier Division", (DWORD)0x9CF8B0},
	{"Northern Irish League First Division", (DWORD)0x9CF8B4},
	{"Northern Irish League Lower Division", (DWORD)0x9CF8B8},
	{"Northern Irish Charity Shield", (DWORD)0x9CF8BC},
	{"Northern Irish Cup", (DWORD)0x9CF8C0},
	{"Northern Irish Gold Cup", (DWORD)0x9CF8C4},
	{"Northern Irish League Cup", (DWORD)0x9CF8C8},
	{"Turkish Lower Division", (DWORD)0x9CF8CC},
	{"Turkish 2. Division Category A", (DWORD)0x9CF8D0},
	{"Turkish 2. Division Category B", (DWORD)0x9CF8D4},
	{"Turkish Premier Division", (DWORD)0x9CF8D8},
	{"Turkish 2. Division Category A", (DWORD)0x9CF8DC},
	{"Turkish 2. Division Category B", (DWORD)0x9CF8E0},
	{"Turkish 2. Division Category B G1", (DWORD)0x9CF8E4},
	{"Turkish 2. Division Category B G2", (DWORD)0x9CF8E8},
	{"Turkish 2. Division Category B G3", (DWORD)0x9CF8EC},
	{"Turkish 2. Division Category B G4", (DWORD)0x9CF8F0},
	{"Turkish 2. Division Category B G5", (DWORD)0x9CF8F4},
	{"Turkish FA Cup", (DWORD)0x9CF8F8},
	{"Turkish Football Writers' Association Cup", (DWORD)0x9CF8FC},
	{"Turkish 2. Division Group 1", (DWORD)0x9CF900},
	{"Turkish 2. Division Group 2", (DWORD)0x9CF904},
	{"Turkish 2. Division Group 3", (DWORD)0x9CF908},
	{"Turkish 2. Division Group 4", (DWORD)0x9CF90C},
	{"Turkish 2. Division Group 5", (DWORD)0x9CF910},
	{"Russian Second Division - West", (DWORD)0x9CF914},
	{"Russian Second Division - Central", (DWORD)0x9CF918},
	{"Russian Second Division - South", (DWORD)0x9CF91C},
	{"Russian Second Division - Volga", (DWORD)0x9CF920},
	{"Russian Second Division - Ural", (DWORD)0x9CF924},
	{"Russian Second Division - East", (DWORD)0x9CF928},
	{"Russian First Division", (DWORD)0x9CF92C},
	{"Russian Premier Division", (DWORD)0x9CF930},
	{"Russian Cup", (DWORD)0x9CF934},
	{"Italian C1 Super Cup", (DWORD)0x9CF938},
	{"Greek Super Cup", (DWORD)0x9CF93C},
	{"Croatian Super Cup", (DWORD)0x9CF940},
	{"Polish Super Cup", (DWORD)0x9CF944},
	{"Irish Presidents Cup", (DWORD)0x9CF948},
	{"Welsh Premier Division", (DWORD)0x9CF94C},
	{"Welsh League Cup", (DWORD)0x9CF950},
	{"Welsh Cup", (DWORD)0x9CF954},
	{"Welsh Premier Cup", (DWORD)0x9CF958},
	{"Inter-American Cup", (DWORD)0x9CF95C},
	{"Welsh Lower Division", (DWORD)0x9CF960},
	{"Confederations Cup", (DWORD)0x9CF964},
	{"Brazilian Bahia Lower Division", (DWORD)0x9CF968},
	{"Brazilian Central Lower Division", (DWORD)0x9CF96C},
	{"Brazilian Santa Catarina Lower Division", (DWORD)0x9CF970},
	{"Brazilian Pernambuco Lower Division", (DWORD)0x9CF974},
	{"Brazilian North Lower Division", (DWORD)0x9CF978},
	{"Brazilian Rio de Janeiro Lower Division", (DWORD)0x9CF97C},
	{"Brazilian Northeast Lower Division", (DWORD)0x9CF980},
	{"Brazilian Goiás Lower Division", (DWORD)0x9CF984},
	{"Brazilian Minas Gerais Lower Division", (DWORD)0x9CF988},
	{"Brazilian Paraná Lower Division", (DWORD)0x9CF98C},
	{"Brazilian Gaúcho Lower Division", (DWORD)0x9CF990},
	{"Brazilian North State Championship", (DWORD)0x9CF994},
	{"Brazilian Central State Championship", (DWORD)0x9CF998},
	{"Brazilian São Paulo Lower Division", (DWORD)0x9CF99C},
	{"Brazilian Central Regional Cup", (DWORD)0x9CF9A0},
	{"Brazilian Northeast State Championship", (DWORD)0x9CF9A4},
	{"Brazilian North Regional Cup", (DWORD)0x9CF9A8},
	{"Brazilian National Third Division", (DWORD)0x9CF9AC},
	{"Brazilian Santa Catarina State Championship", (DWORD)0x9CF9B0},
	{"Brazilian Goiás State Championship", (DWORD)0x9CF9B4},
	{"Brazilian Champions Cup", (DWORD)0x9CF9B8},
	{"Brazilian Pernambuco State Championship", (DWORD)0x9CF9BC},
	{"Brazilian Bahia State Championship", (DWORD)0x9CF9C0},
	{"Brazilian Northeast Regional Cup", (DWORD)0x9CF9C4},
	{"Brazilian Gaúcho State Championship", (DWORD)0x9CF9C8},
	{"Brazilian South-Minas Regional Cup", (DWORD)0x9CF9CC},
	{"Brazilian Paraná State Championship", (DWORD)0x9CF9D0},
	{"Brazilian Minas Gerais State Championship", (DWORD)0x9CF9D4},
	{"Brazilian Rio-São Paulo Tournement", (DWORD)0x9CF9D8},
	{"Brazilian Rio de Janeiro State Championship", (DWORD)0x9CF9DC},
	{"Brazilian National Second Division", (DWORD)0x9CF9E0},
	{"Brazilian São Paulo State Championship", (DWORD)0x9CF9E4},
	{"Brazilian Cup", (DWORD)0x9CF9E8},
	{"Brazilian National First Division", (DWORD)0x9CF9EC},
	{"Irish Munster Senior Cup", (DWORD)0x9CF9F0},
	{"Irish Leinster Senior Cup", (DWORD)0x9CF9F4},
	{"Korean Super Cup", (DWORD)0x9CF9F8},
	{"Korean League Cup", (DWORD)0x9CF9FC},
	{"Korean League", (DWORD)0x9CFA00},
	{"Korean FA Cup", (DWORD)0x9CFA04},
};

void inject_names_full()
{
	for (const auto& [key, value] : club_rename_short) {
		cm3_clubs* to_rename = find_club(key.c_str());
		if (to_rename) {
			strcpy_s((*to_rename).ClubNameShort, value.c_str());
		}
	}
	for (const auto& [key, value] : club_rename_long) {
		cm3_clubs* to_rename = find_club(key.c_str());
		if (to_rename) {
			strcpy_s((*to_rename).ClubName, value.c_str());
		}
	}
}

extern "C" _declspec(naked) int inject_names()
{
	_asm
	{
		pushad
	}
	inject_names_full();
	_asm
	{
		popad
		ret
	}
}

map<string, char*> new_names_map_long = {
	{"Portuguese Premier League", "Liga Portugal 1"}
};

map<string, char*> new_names_map_short = {
	{"Portuguese Premier League", "Liga 1"}
};

map<string, char*> new_names_map_tla = {
	{"Portuguese Premier League", "LP1"}
};

int setup_9cf_leagues(char* league_name, DWORD league_id) {
	auto names_map = league_dword_match_original;
	// Change database names
	cm3_club_comps* comp_data = &(*club_comps)[league_id];
	string league_name_str = string(league_name);
	auto new_val_long = new_names_map_long.find(league_name_str);
	if (new_val_long != new_names_map_long.end()) {
		strcpy_s(comp_data->ClubCompName, new_val_long->second);
	}
	auto new_val_short = new_names_map_short.find(league_name_str);
	if (new_val_short != new_names_map_short.end()) {
		strcpy_s(comp_data->ClubCompNameShort, new_val_short->second);
	}
	auto new_val_tla = new_names_map_tla.find(league_name_str);
	if (new_val_tla != new_names_map_tla.end()) {
		strcpy_s(comp_data->ClubCompNameThreeLetter, new_val_tla->second);
	}
	// Fill out 9CF codes
	auto it = names_map.begin();
	while (it != names_map.end()) {
		char* key = it->first;
		if (_strcmpi(key, league_name) == 0)
		{
			while (it != names_map.end() && it->first == key) {
				WriteDWORD(it->second, league_id);
				it++;
			}
			return 1;
		}
		else {
			auto find_name_edited = new_names_map_long.find(string(key));
			if (find_name_edited != new_names_map_long.end() && _strcmpi(find_name_edited->second, league_name) == 0) {
				while (it != names_map.end() && it->first == key) {
					WriteDWORD(it->second, league_id);
					it++;
				}
				return 1;
			}
			else {
				it++;
			}
		}
	}
	return 1;
}

void setup_name_injection()
{
	// Add call to our name function after all player setups have been loaded
	DWORD func_addr = (DWORD)inject_names;
	//PatchFunction(0x005CCCC1, func_addr);
	PatchFunction(0x60EFD0, (DWORD)setup_9cf_leagues);
}