#pragma once

#include "Argentina\arg_setup.h"
#include "Australia\aus_setup.h"
#include "Belgium\bel_setup.h"
#include "Brazil\bra_setup.h"
#include "Croatia\cro_setup.h"
#include "Czech Republic\cze_setup.h"
#include "Denmark\den_setup.h"
#include "England\eng_setup.h"
#include "Finland\fin_setup.h"
#include "France\fra_setup.h"
#include "Germany\ger_setup.h"
#include "Greece\gre_setup.h"
#include "Holland\hol_setup.h"
#include "Ireland\irl_setup.h"
#include "Italy\ita_setup.h"
#include "Japan\jpn_setup.h"
#include "Northern Ireland\nir_setup.h"
#include "Norway\nor_setup.h"
#include "Poland\pol_setup.h"
#include "Portugal\por_setup.h"
#include "Russia\rus_setup.h"
#include "Scotland\sco_setup.h"
#include "South Korea\kor_setup.h"
#include "Spain\spa_setup.h"
#include "Sweden\swe_setup.h"
#include "Turkey\tur_setup.h"
#include "USA\usa_setup.h"
#include "Wales\wal_setup.h"

#include "FIFA\fifa_club_setup.h"
#include "AFC\afc_setup.h"
#include "CAF\caf_setup.h"
#include "CONCACAF\concacaf_setup.h"
#include "CONMEBOL\conmebol_setup.h"
#include "OFC\ofc_setup.h"
#include "UEFA\uefa_setup.h"

void setup_leagues_setup();